# Creating numpy arrays

<ol>
   <li> using np.array()  // 1-D and 2-D</li>
    <li>using np.zeros/ones() </li>
    <li>using np.arange() </li>
    <li>using np.linspace() </li>
    <li>using copy() </li>
    <li>using identity() </li>
</ol>
<br>

In [2]:
import numpy as np

<br>

In [3]:
# 1-D array
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
type(arr1)

numpy.ndarray

<br>

In [5]:
# 2-D array
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

<br>

In [6]:
arr3 = np.zeros((2,3))  # zeros((row,column)) 
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

<br>

In [8]:
arr4 = np .ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

<br>

In [9]:
arr5 = np.identity(4)
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

<br>

In [11]:
arr6 = np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr6 = np.arange(3,20)
arr6

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
arr6 = np.arange(3,20,2)
arr6

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

<br>

In [16]:
# linspace(start,end,items), all the distance of items are equall 

arr7 = np.linspace(10,20,10) 
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

<br>

In [18]:
arr8 = np.copy(arr7)
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

<br>