In [1]:
import numpy as np

In [2]:
np.random.random() # range 0 to 1

0.04313455365630248

In [11]:
# give us same number again and again

np.random.seed(1)
np.random.random() # range 0 to 1

0.417022004702574

In [13]:
# give us float numbers in given range

np.random.uniform(3,10) 

3.000800623721414

In [14]:
# uniform(low,high,size)

np.random.uniform(1,100,10).reshape(2,5)

array([[30.93092469, 15.52883319, 10.14152088, 19.43976093, 35.21051198],
       [40.27997995, 54.34285667, 42.50025693, 68.83673054, 21.24077272]])

In [15]:
np.random.randint(1,100,15).reshape(3,5)

array([[29, 30, 15, 51, 69],
       [88, 88, 95, 97, 87],
       [14, 10,  8, 64, 62]])

In [16]:
a = np.random.randint(1,10,6)
a

array([7, 2, 1, 2, 9, 9])

In [17]:
np.max(a)

9

In [18]:
np.min(a)

1

In [19]:
np.argmax(a)   # index of maximum number

4

In [20]:
a[np.argmax(a)]   # getting maximum number from index

9

In [21]:
np.argmin(a)

2

In [22]:
a[np.argmin(a)]   # getting minimum number from index

1

In [23]:
a = np.random.randint(1,10,6)
a

array([4, 9, 8, 4, 7, 6])

In [24]:
a[a%2==1]=-1  # inplace change

In [25]:
a

array([ 4, -1,  8,  4, -1,  6])

In [30]:
a = np.random.randint(1,100,6) # Orginal array
a

array([50, 58,  4, 69, 25, 44])

In [31]:
# where(condition,true,false)

out = np.where(a%2==1,-1,a)  # Orginal array don't affected, it is stored in out variable
out

array([50, 58,  4, -1, -1, 44])

In [32]:
a

array([50, 58,  4, 69, 25, 44])

In [33]:
a = np.random.randint(1,100,10) # Orginal array
a

array([77, 27, 53, 81, 42, 83, 16, 65, 69, 26])

In [35]:
b = np.sort(a)
b

array([16, 26, 27, 42, 53, 65, 69, 77, 81, 83])

In [39]:
a = np.random.randint(1,100,10) # Orginal array
a

array([24, 28, 38, 58, 84, 39,  9, 33, 35, 11])

In [40]:
np.percentile(a,25) # The 25th percentile is 25, which means 25% of the values are below 25, and  75% are higher.

25.0

In [41]:
np.percentile(a,50)  # The 50th percentile is 34, which means 50% of the values are below 34, and  50% are higher.

34.0

In [42]:
np.percentile(a,100)  # The 100th percentile is 84, which means 100% of the values are below 84.

84.0