# Properties & Attributes

<ol>
   <li>shape</li>
    <li>nDim </li>
    <li>size </li>
    <li>itemsize </li>
    <li>Dtype </li>
    <li>astype() </li>
</ol>
<br>

In [1]:
import numpy as np

## Shape:

In [2]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
arr1.shape

(5,)

In [4]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr2.shape

(2, 3)

In [8]:
arr3 = np.array([[[1,2],[2,3]],[[4,5],[6,7]]])
arr3

array([[[1, 2],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [9]:
arr3.shape

(2, 2, 2)

(2, 2, 2) (row,column, number of matrix)

##  Dimentional:

In [10]:
arr3.ndim

3

In [11]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr2.ndim

2

In [13]:
arr1

array([1, 2, 3, 4, 5])

In [14]:
arr1.ndim

1

## Size & item-size:

In [15]:
arr1

array([1, 2, 3, 4, 5])

In [16]:
arr1.size

5

In [17]:
arr1.itemsize  # integer 4 byte

4

In [18]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
arr3.size

6

In [20]:
arr3.itemsize # float 8 byte

8

In [21]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr2.size

6

## Data Type :

In [23]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

arr2.dtype 

In [25]:
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
arr3.dtype

dtype('float64')

## Change Data-type:

In [31]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
arr2.dtype

dtype('int32')

In [34]:
arr2.astype('float')

array([[1., 2., 3.],
       [4., 5., 6.]])

In [35]:
arr2.dtype # not changed in real array

dtype('int32')

In [36]:
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
arr3.astype('int')

array([[0, 0, 0],
       [0, 0, 0]])