In [1]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([4,5,6,7,8])

In [4]:
arr1-arr2

array([-3, -3, -3, -3, -3])

In [5]:
arr1 * arr2   # vector multiplication

array([ 4, 10, 18, 28, 40])

In [6]:
arr1 * 1    # scaler multiplication

array([1, 2, 3, 4, 5])

In [7]:
arr2

array([4, 5, 6, 7, 8])

In [8]:
arr2 > 3

array([ True,  True,  True,  True,  True])

In [10]:
# dot products

arr3 = np.arange(6).reshape(2,3)
arr4 = np.arange(6,12).reshape(3,2)

In [11]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [12]:
arr2.dot(arr3) 

ValueError: shapes (5,) and (2,3) not aligned: 5 (dim 0) != 2 (dim 0)

In [13]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [14]:
arr4.max()

11

In [15]:
arr4.min()

6

In [16]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [18]:
arr4.min(axis=0)   # minimum item of each column

array([6, 7])

In [19]:
arr4.min(axis=1)   # minimum item of each row

array([ 6,  8, 10])

In [20]:
arr4.sum()

51

In [21]:
arr4.sum(axis=0)   # sum column wise (6+8+10)=24 & (7+9+11)=27

array([24, 27])

In [22]:
arr4.sum(axis=1)   # sum row wise (6+7)=13 & (8+9+)=17 & (10+11)=21

array([13, 17, 21])

In [23]:
arr4.mean()   # you can both column and rows

8.5

In [25]:
# standard deviation

arr4.std()   # you can both column and rows

1.707825127659933

In [26]:
np.median(arr4)

8.5

In [27]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [28]:
np.exp(arr4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])