# Reshaping Numpy arrays
<ol>
    <li>Ravel</li>
    <li>Reshape</li>
    <li>Transpose</li>
    <li>Stacking</li>
    <li>Splitting</li>
</ol>

In [2]:
import numpy as np

In [4]:
arr1 = np.arange(6).reshape(3,2)
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [5]:
# n-D to 1D
arr1.ravel()

array([0, 1, 2, 3, 4, 5])

In [6]:
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [7]:
arr1.transpose()

array([[0, 2, 4],
       [1, 3, 5]])

In [9]:
arr2 = np.arange(6).reshape(2,3)
arr3 = np .arange(7,13).reshape(2,3)

In [10]:
arr3

array([[ 7,  8,  9],
       [10, 11, 12]])

In [11]:
arr2

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
np.hstack((arr2,arr3)) # hstack = horizontal stack

array([[ 0,  1,  2,  7,  8,  9],
       [ 3,  4,  5, 10, 11, 12]])

In [13]:
np.hstack((arr2,arr1))  # need same shape 

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

In [14]:
np.vstack((arr2,arr3)) # vstack = vertical stack

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
arr3

array([[ 7,  8,  9],
       [10, 11, 12]])

In [18]:
np.hsplit(arr3,3)   # hsplit(array,how many parts)

[array([[ 7],
        [10]]),
 array([[ 8],
        [11]]),
 array([[ 9],
        [12]])]

In [19]:
np.vsplit(arr3,2)

[array([[7, 8, 9]]), array([[10, 11, 12]])]