In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,100,20).reshape(4,5)  # randint(low, high, size)
arr

array([[24, 85, 71, 19,  8],
       [42, 17, 39, 24, 70],
       [37, 19, 66, 65,  8],
       [21, 14, 57, 98, 10]])

In [3]:
# Indexing with Boolean Arrays
arr[arr>50]

array([85, 71, 70, 66, 65, 57, 98])

In [4]:
arr[(arr>50) & (arr%2 != 0)]

array([85, 71, 65, 57])

In [5]:
arr

array([[24, 85, 71, 19,  8],
       [42, 17, 39, 24, 70],
       [37, 19, 66, 65,  8],
       [21, 14, 57, 98, 10]])

In [6]:
arr[(arr>50) & (arr%2 != 0)] = 0

In [7]:
arr

array([[24,  0,  0, 19,  8],
       [42, 17, 39, 24, 70],
       [37, 19, 66,  0,  8],
       [21, 14,  0, 98, 10]])