In [2]:
import numpy as np

In [3]:
a1 = np.arange(8).reshape(2,4)
a2 = np.arange(8,16).reshape(2,4)

In [4]:
a1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [5]:
a2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [6]:
a1 + a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [8]:
a3 = np.arange(9).reshape(3,3)
a4 = np.arange(3).reshape(1,3)

In [9]:
a3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
a4

array([[0, 1, 2]])

In [11]:
a3 + a4

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

# Broadcasting

#### The term broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations. Arithmetic operations on arrays are usually done on corresponding elements. If two arrays are of exactly the same shape, then these perations are smoothly performed.

#### If the dimensions of two arrays are dissimilar, element-to-element operations are not possible. However, operations on arrays of non-similar shapes is still possible in NumPy, because of the broadcasting capability. The smaller array is broadcast to the size of the larger array so that they have compatible shapes.

## Rules for Broadcasting

In [14]:
# if x=m and y=n operation will take place 

a1 = np.arange(8).reshape(2,4)
a2 = np.arange(8,16).reshape(2,4)

In [15]:
a1+a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [18]:
# if x=1 and y=n then also operation will take place (same dimention)

a3 = np.arange(3).reshape(1,3)
a4 = np.arange(12).reshape(4,3)

In [19]:
a3

array([[0, 1, 2]])

In [20]:
a4

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [17]:
a3+a4

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [21]:
# if x=1 and y!=n then also operation will not take place 

a5 = np.arange(3).reshape(1,3)
a6 = np.arange(16).reshape(4,4)

In [22]:
a5

array([[0, 1, 2]])

In [23]:
a6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [24]:
a5+a6

ValueError: operands could not be broadcast together with shapes (1,3) (4,4) 

In [29]:
# if y=1 and x==m then also operation will take place even if
# they are not in same dimention

a7 = np.arange(4).reshape(4,1)
a8 = np.arange(12).reshape(4,3)

In [27]:
a7

array([[0],
       [1],
       [2],
       [3]])

In [30]:
a8

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [31]:
a7+a8

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [32]:
#if x=1 and y=1 then  operation will take place no matter what

a9 = np.arange(1).reshape(1,1)
a10 = np.arange(12).reshape(4,3)

In [33]:
a9

array([[0]])

In [34]:
a10

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [35]:
a9+a10

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [38]:
# if they are in different dimention
a11 = np.arange(4)
a12 = np.arange(12).reshape(3,4)   # 4==4

In [39]:
a11+a12

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])